name: architecture_cli
description: Architecture_CLI is a  package designed to streamline the folder structure creation process
version: 0.0.2
homepage: https://devhammad.com/

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.4.0
  path: ^1.8.3

executables:
  arch_cli: architecture_cli
  folder_cli: architecture_cli
  architecture_cli:
